### ISSUE TITLE
Can't access token in form submission

### ISSUE THREAD

**Issue by smantzavinos** [ericdude4/shopifex#17]
I am having an issue accessing the token submitted in a form following the pattern from the readme. The readme example includes

```elixir
<%= form_for :foo, Routes.foo_path(MyApp.Endpoint, :new), fn f -> %>
  <%= hidden_input, f, :token, value: Guardian.Plug.current_token(conn) %>
  <%= submit "Submit" %>
<% end %>
```
The problem I am seeing is that this results in the token being passed in the params under `params.foo.token`. `Shopifex.Plug.ShopifySession.get_token_from_conn\1` expects the token to be in `params.token`. However, I see no way to get it there with a hidden input in a form.

I have a proposed change that I have made locally and is working. Since the hidden input can take any atom as it's input, we can pass the same atom to all hidden inputs (in all forms) so the token is always found in the same place. For example:

```elixir
<%= form_for :foo, Routes.foo_path(MyApp.Endpoint, :new), fn f -> %>
  <%= hidden_input :hidden_input, :token, value: Guardian.Plug.current_token(@conn) %>
  <%= submit "Submit" %>
<% end %>
```

And now we can add another clause to `Shopifex.Plug.ShopifySession.get_token_from_conn\1`
```elixir
# existing
defp get_token_from_conn(%Plug.Conn{params: %{"token" => token}}), do: token

# new
defp get_token_from_conn(%Plug.Conn{params: %{"hidden_input" => %{"token" => token}}}), do: token
```

My only confusion with this approach is that it goes against the suggestion made by Dockyard in their [Tips for Token Article](https://dockyard.com/blog/2020/01/14/tips-for-tokens) where they suggest requiring tokens in the Authorization header (as you have shown in the SPA example). This seems like a good idea but I don't see any way to get the token in the Authorization header.

If you agree with my solution I could submit a PR with the change.

**Comment by smantzavinos** [comment]
I went ahead and opened up a pull request with this change. However, this if the first time I am testing with v0.6 and I am getting a compilation error unrelated to my change. I haven't had a chance to do much digging yet but I am getting:

```
== Compilation error in file lib/shopifex_web/views/error_view.ex ==
** (CompileError) lib/shopifex_web/views/error_view.ex:2: module ReactPhoenix.ClientSide is not loaded and could not be found
    expanding macro: ShopifexWeb.__using__/1
    lib/shopifex_web/views/error_view.ex:2: ShopifexWeb.ErrorView (module)
    (elixir 1.11.3) expanding macro: Kernel.use/2
    lib/shopifex_web/views/error_view.ex:2: ShopifexWeb.ErrorView (module)
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

```

**Comment by smantzavinos** [comment]
Thank you! I did not like the "hidden_input" method either and this is clearly the much better solution.

I have updated my PR to be a documentation update instead. 

In regards to the other compile issue I saw, not sure what happened. After cleaning deps it is working now. I was using v0.5 previously for reference.
