### ISSUE TITLE
** (ArgumentError) invalid option :null for field/3

### ISSUE THREAD

**Issue by imrying** [ericdude4/shopifex#42]
After initial setup when trying to migrate i get the following error:
```
Compiling 22 files (.ex)

== Compilation error in file lib/oko_shipping/shopify_shops/shopify_shop.ex ==
** (ArgumentError) invalid option :null for field/3
    (ecto 3.8.4) lib/ecto/schema.ex:2208: Ecto.Schema.check_options!/3
    (ecto 3.8.4) lib/ecto/schema.ex:1917: Ecto.Schema.__field__/4
    lib/oko_shipping/shopify_shops/shopify_shop.ex:6: (module)
```
This error comes after i have recompiled where i got a warning saying:
```
warning: OkoShipping.ShopifyPaymentGuard.list_available_plans_for_guard/2 is undefined (module OkoShipping.ShopifyPaymentGuard is not available or is yet to be defined)
  lib/shopifex_web/views/payment_view.ex:8: ShopifexWeb.PaymentView.available_plans/2 
```

**Comment by ericdude4** [comment]
@imrying Thanks for being a guinea pig for the `mix shopifex.install` mix tool. I haven't used it in a while, so I guess it was no longer working with new Phoenix versions. I have updated the package with version `2.1.5`, which should fix the first issue. Let me know if the second issue still persists, I didn't try to fix that one.

**Comment by imrying** [comment]
Cool, i will test it tomorow ;-)
